#ifndef C_PROJECT_SECOND_EXE_H
#define C_PROJECT_SECOND_EXE_H

#include "table.h"
#include "encoding.h"


/**
 * @brief Performs the second pass of the assembler process.
 *
 * This function carries out the second pass of the assembler, which includes checking for errors, merging code and data segments,
 * replacing externs and labels, converting code into octal format, and generating the output files. The function uses the output
 * from the first pass, along with the label table, instruction counter (IC), data counter (DC), and information about externs and
 * entries. During this pass, the function also checks for errors and sets the 'error_found' flag if any issues are detected.
 *
 * @param file_name         The name of the source file being assembled (used for output file naming).
 * @param label_table       A pointer to an array of label_address structures containing label definitions.
 * @param IC                The instruction counter.
 * @param DC                The data counter.
 * @param label_table_line  The total number of entries in the label table.
 * @param externs_count     The total number of extern labels.
 * @param entries_count     The total number of entry labels.
 * @param code              A pointer to an array of code_conv structures containing assembled code.
 * @param data              A pointer to an array of code_conv structures containing assembled data.
 * @param externs           A pointer to an array of other_table structures containing extern label information.
 * @param entries           A pointer to an array of other_table structures containing entry label information.
 * @param error_found       A flag indicating if any errors were found during the second pass (0 - no errors, 1 - errors found).
 * @return Returns 1 if the second pass completes successfully without errors, otherwise returns 0.
 */
int execute_second_pass(char *file_name, label_address *label_table, int IC, int DC, int label_table_line, \
    int externs_count, int entries_count, code_conv *code, code_conv *data, other_table *externs, other_table *entries, \
    int error_found);


/**
 * @brief Converts assembled binary code into octal format and writes it to an output file.
 *
 * This function processes the binary code stored in the 'code' array, converts each piece of machine code into its octal format,
 * and writes the results to an output file with a `.ob` extension. The output file starts with a line containing the IC and DC values
 * separated by a space, followed by lines with the octal representation of each machine code in the 'code' array.
 *
 * @param code        A pointer to an array of code_conv structures containing the binary code generated by the assembler.
 * @param count       The total number of instructions and data entries in the 'code' array.
 * @param file_name   The name of the source file being processed (used for output file naming).
 * @param IC          The instruction counter.
 * @param DC          The data counter.
 * @return Returns 1 if the conversion and writing to the output file succeed, otherwise returns 0.
 */
int convert_code_to_octal(code_conv *code, int count, char *file_name, int IC, int DC);


#endif
